name: Deploy Application

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List files for debugging
      run: ls -la
      shell: bash

    - name: Setup FTP deployment
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.nibiz.online
        username: advposadmin@advposadmin.nibiz.online
        password: bn+2IF01:lxE4I
        local-dir: ./
        server-dir: /
        exclude: .gitignore
