name: Deploy Application

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List files for debugging
      run: ls -la
      shell: bash

    - name: Setup FTP deployment
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.supermanbd.com
        username: superman_nibiz@supermanbd.com	
        password: superman_nibiz@supermanbd.com	
        local-dir: ./
        server-dir: /public_html/
        exclude: .gitignore
